import React, { useState } from 'react';
import { X, Search, BookOpen, ExternalLink } from 'lucide-react';

export interface GlossaryItem {
  term: string;
  definition: string;
  category: 'Entities' | 'Forensic Patterns' | 'Legal & Regulatory' | 'Blockchain Infra';
}

export const GLOSSARY_TERMS: GlossaryItem[] = [
  {
    term: 'VASP (Virtual Asset Service Provider)',
    definition: 'Any entity or exchange offering custodial wallet, fiat conversion, or crypto brokerage services. Critical in investigations as VASPs possess real-world KYC identity records and fiat bank account linkages.',
    category: 'Entities'
  },
  {
    term: 'Deposit Address',
    definition: 'A unique temporary receiving address generated by a centralized exchange (VASP) assigned to a specific customer account. Funds reaching a deposit address are swept to a central hot wallet.',
    category: 'Entities'
  },
  {
    term: 'Hot Wallet',
    definition: 'An active, internet-connected omnibus wallet maintained by an exchange or service to fulfill real-time customer deposits and withdrawals.',
    category: 'Entities'
  },
  {
    term: 'Non-Custodial Wallet',
    definition: 'A private blockchain wallet where only the end-user holds the cryptographic private keys. No central intermediary can freeze these addresses without obtaining the mnemonic seed.',
    category: 'Blockchain Infra'
  },
  {
    term: 'Burner Wallet',
    definition: 'A disposable, single-use intermediate wallet utilized by scammers to quickly transit and layer illicit funds before immediate abandonment.',
    category: 'Forensic Patterns'
  },
  {
    term: 'Layering',
    definition: 'The second stage of money laundering involving rapid, complex multi-hop transfers across multiple wallets and blockchains to sever direct evidentiary connection to the victim deposit.',
    category: 'Forensic Patterns'
  },
  {
    term: 'Peel Chain',
    definition: 'A structured laundering technique where a large input is repeatedly split into one large continuing transfer (to the next hop) and one small peel (often diverted to an off-ramp or cashout).',
    category: 'Forensic Patterns'
  },
  {
    term: 'Cross-Chain Bridge',
    definition: 'A cryptographic smart contract protocol allowing assets on one blockchain (e.g., Tron USDT) to be locked, and synthetic or wrapped equivalents released on another chain (e.g., BSC or Arbitrum).',
    category: 'Blockchain Infra'
  },
  {
    term: 'Mixer / Tumbler',
    definition: 'A privacy-enhancing pooling protocol (e.g., Tornado Cash, VeilMix) that commingles funds from hundreds of users to break deterministic on-chain linkability. Tracing relies on probabilistic matching.',
    category: 'Forensic Patterns'
  },
  {
    term: 'Taint Propagation',
    definition: 'The forensic methodology of calculating what percentage of a wallet’s funds derive from criminal proceeds. ChainNetra implements Haircut (proportional), FIFO (first-in first-out), and Poison models.',
    category: 'Forensic Patterns'
  },
  {
    term: 'NCRP (National Cybercrime Reporting Portal)',
    definition: 'The Government of India centralized portal for citizen reporting of cybercrimes and financial frauds. Provides the initial complainant wallet and financial loss statement.',
    category: 'Legal & Regulatory'
  },
  {
    term: 'SAHYOG',
    definition: 'Law-enforcement coordination framework facilitating real-time data sharing and interstate cyber fraud attribution across state police headquarters.',
    category: 'Legal & Regulatory'
  },
  {
    term: 'Freeze Request',
    definition: 'A formal law-enforcement legal demand served to a VASP compliance desk under applicable statutory provisions, directing the immediate restraint of suspect deposit balances and preservation of KYC.',
    category: 'Legal & Regulatory'
  },
  {
    term: 'KYC (Know Your Customer)',
    definition: 'Mandatory customer identity verification records gathered by VASPs, including government IDs, biometric photographs, phone numbers, IP audit trails, and bank account numbers.',
    category: 'Legal & Regulatory'
  }
];

interface GlossaryDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  initialSearch?: string;
}

export const GlossaryDrawer: React.FC<GlossaryDrawerProps> = ({ isOpen, onClose, initialSearch = '' }) => {
  const [query, setQuery] = useState(initialSearch);

  if (!isOpen) return null;

  const filtered = GLOSSARY_TERMS.filter(
    (item) => item.term.toLowerCase().includes(query.toLowerCase()) || item.definition.toLowerCase().includes(query.toLowerCase())
  );

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/60 backdrop-blur-sm animate-in fade-in">
      <div className="w-full max-w-md bg-panel border-l border-hairline h-full flex flex-col shadow-2xl animate-in slide-in-from-right duration-200">
        {/* Header */}
        <div className="p-4 border-b border-hairline flex items-center justify-between bg-raised/40">
          <div className="flex items-center gap-2">
            <BookOpen className="w-5 h-5 text-amber" />
            <h2 className="font-bold text-sm tracking-wide text-text-primary">Crypto-Forensic Glossary</h2>
          </div>
          <button 
            onClick={onClose}
            className="p-1 rounded hover:bg-raised text-text-muted hover:text-text-primary transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Search Input */}
        <div className="p-3 border-b border-hairline">
          <div className="relative">
            <Search className="w-4 h-4 absolute left-3 top-2.5 text-text-muted" />
            <input
              type="text"
              placeholder="Search forensic terminology, laws, acronyms..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="w-full bg-ink border border-hairline rounded-lg pl-9 pr-3 py-2 text-xs text-text-primary placeholder:text-text-muted focus:outline-none focus:border-amber"
              autoFocus
            />
          </div>
        </div>

        {/* Terms List */}
        <div className="flex-1 overflow-y-auto p-4 space-y-3">
          {filtered.length === 0 ? (
            <div className="text-center py-10 text-text-muted text-xs">
              No matching terminology found for "{query}".
            </div>
          ) : (
            filtered.map((item, idx) => (
              <div key={idx} className="p-3 rounded-lg bg-raised/50 border border-hairline hover:border-amber/40 transition-colors">
                <div className="flex items-center justify-between mb-1.5">
                  <h3 className="text-xs font-bold text-amber">{item.term}</h3>
                  <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-panel border border-hairline text-text-muted">
                    {item.category}
                  </span>
                </div>
                <p className="text-xs text-text-primary/90 leading-relaxed">
                  {item.definition}
                </p>
              </div>
            ))
          )}
        </div>

        {/* Footer info */}
        <div className="p-3 border-t border-hairline bg-ink text-[11px] text-text-muted text-center font-mono">
          ChainNetra Standardized Law Enforcement Field Reference
        </div>
      </div>
    </div>
  );
};
