import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  FileText, Download, CheckCircle, ShieldCheck, 
  ExternalLink, Sparkles, PlusCircle, QrCode 
} from 'lucide-react';
import toast from 'react-hot-toast';
import { api } from '../lib/api';
import { useAppStore } from '../stores/useAppStore';

export const Reports: React.FC = () => {
  const navigate = useNavigate();
  const explainMode = useAppStore((s) => s.explainMode);
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const loadReports = async () => {
    try {
      setLoading(true);
      const res = await api.getReports();
      setReports(res.reports || []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const handleGenerateReport = async (caseId: number) => {
    try {
      const res = await api.generateReport(caseId);
      toast.success(`Generated forensic dossier: ${res.report.report_number}`);
      loadReports();
    } catch (e) {
      toast.error('Report generation failed');
    }
  };

  return (
    <div className="space-y-4 animate-in fade-in duration-200">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 pb-2 border-b border-hairline">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-text-primary flex items-center gap-2">
            Forensic Investigation Reports & Dossiers
            <span className="text-xs px-2 py-0.5 rounded font-mono font-bold bg-amber/15 border border-amber/30 text-amber">
              STANDARDIZED EVIDENCE DOSSIERS
            </span>
          </h1>
          <p className="text-xs text-text-muted mt-0.5">
            Court-admissible PDF reports featuring cryptographic SHA-256 hashes, QR verification, and statutory digital evidence certificates.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => handleGenerateReport(1)}
            className="px-4 py-2 rounded-lg bg-amber text-ink font-bold text-xs hover:bg-amber-400 transition-colors flex items-center gap-1.5 shadow"
          >
            <PlusCircle className="w-4 h-4" />
            Generate Case Zero Dossier
          </button>

          <button
            onClick={() => navigate('/verify')}
            className="px-3.5 py-2 rounded-lg bg-raised hover:bg-hairline border border-hairline text-xs font-semibold text-text-primary transition-colors flex items-center gap-1.5"
          >
            <ShieldCheck className="w-4 h-4 text-mint" />
            Verification Portal
          </button>
        </div>
      </div>

      {explainMode && (
        <div className="p-3 bg-cyan/10 border border-cyan/30 rounded-lg text-xs text-cyan flex items-start gap-2.5">
          <Sparkles className="w-4 h-4 shrink-0 mt-0.5" />
          <div>
            <span className="font-bold">Evidence Integrity Standard:</span> Each PDF is sealed with a dual SHA-256 hash:
            the hash of the underlying canonical JSON trace snapshot, and the hash of the generated PDF itself.
            An embedded QR code on the cover page allows judicial magistrates or VASP compliance officers to independently verify authenticity.
          </div>
        </div>
      )}

      {/* Reports Table */}
      <div className="bg-panel border border-hairline rounded-xl overflow-hidden shadow">
        <div className="p-3 border-b border-hairline flex items-center justify-between">
          <h3 className="text-xs font-bold text-text-primary tracking-wide">
            Sealed Case Reports ({reports.length})
          </h3>
          <span className="text-[10px] font-mono text-text-muted">A4 Format • Tamper-Evident</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead className="bg-raised/70 border-b border-hairline text-[10px] text-text-muted uppercase">
              <tr>
                <th className="p-3">Report Number</th>
                <th className="p-3">Case ID</th>
                <th className="p-3">Generated By</th>
                <th className="p-3">Snapshot SHA-256 Hash</th>
                <th className="p-3">PDF SHA-256 Hash</th>
                <th className="p-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-hairline">
              {reports.map((r) => (
                <tr key={r.id} className="hover:bg-raised/40 transition-colors">
                  <td className="p-3 font-bold text-text-primary flex items-center gap-1.5">
                    <FileText className="w-4 h-4 text-amber" />
                    <span>{r.report_number}</span>
                  </td>

                  <td className="p-3 font-bold text-cyan">
                    CASE-{r.case_id.toString().padStart(4, '0')}
                  </td>

                  <td className="p-3 text-text-muted">
                    {r.generated_by}
                  </td>

                  <td className="p-3 text-text-muted truncate max-w-[130px]" title={r.snapshot_sha256}>
                    {r.snapshot_sha256}
                  </td>

                  <td className="p-3 text-mint truncate max-w-[130px]" title={r.sha256_hash}>
                    {r.sha256_hash}
                  </td>

                  <td className="p-3 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <a
                        href={`http://localhost:8000/api/v1/reports/${r.id}/download`}
                        target="_blank"
                        rel="noreferrer"
                        className="px-2.5 py-1 rounded bg-raised hover:bg-hairline border border-hairline text-amber font-semibold text-xs inline-flex items-center gap-1"
                      >
                        <Download className="w-3.5 h-3.5" /> PDF
                      </a>

                      <button
                        onClick={() => navigate(`/verify/${r.sha256_hash}`)}
                        className="px-2.5 py-1 rounded bg-raised hover:bg-hairline border border-hairline text-mint font-semibold text-xs inline-flex items-center gap-1"
                        title="Verify cryptographic authenticity"
                      >
                        <ShieldCheck className="w-3.5 h-3.5" /> Verify
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
