import os
import sys
import yaml
import argparse
from datetime import date, datetime
from typing import Dict, Any, Optional, List, Literal
from pathlib import Path
from pydantic import BaseModel, Field, field_validator, model_validator

LEGAL_DISCLAIMER = "Draft generated by software. Review by the investigating officer / legal officer required before use."

class ProvisionEntry(BaseModel):
    key: str
    label: str
    current_code: str
    current_section: str
    legacy_code: Optional[str] = None
    legacy_section: Optional[str] = None
    applicability_rule: Literal["offence_date", "proceeding_pending_at_commencement", "none"]
    effective_from: Optional[date] = None
    verification: Literal["primary", "secondary", "unverified"]
    verified_source: str
    verified_on: Optional[date] = None
    needs_legal_review: bool
    note: Optional[str] = None

    @model_validator(mode="after")
    def validate_verification_and_review(self) -> "ProvisionEntry":
        if self.verification == "primary":
            if self.verified_on is None:
                raise ValueError(f"Primary verification for '{self.key}' requires a verified_on date.")
            if self.needs_legal_review:
                raise ValueError(f"Primary verification entry '{self.key}' should have needs_legal_review=False.")
        else:
            if not self.needs_legal_review:
                raise ValueError(f"Non-primary entry '{self.key}' must have needs_legal_review=True.")
        return self

class CommencementInfo(BaseModel):
    date: date
    verification: Literal["primary", "secondary", "unverified"]
    note: Optional[str] = None
    todo: Optional[str] = None

class LegalProvisionsConfig(BaseModel):
    commencement: Dict[str, CommencementInfo]
    provisions: Dict[str, ProvisionEntry]

    @field_validator("provisions")
    @classmethod
    def validate_provisions_keys(cls, v: Dict[str, ProvisionEntry]) -> Dict[str, ProvisionEntry]:
        for k, entry in v.items():
            if k != entry.key:
                raise ValueError(f"Dictionary key '{k}' does not match entry.key '{entry.key}'")
        return v

_REGISTRY: Optional[LegalProvisionsConfig] = None

def get_provisions_yaml_path() -> Path:
    # First check relative to this file
    this_dir = Path(__file__).resolve().parent
    yaml_path = this_dir / "provisions.yaml"
    if yaml_path.exists():
        return yaml_path
    # Try backend/app/legal/provisions.yaml
    root_dir = Path(os.getcwd())
    candidate = root_dir / "backend" / "app" / "legal" / "provisions.yaml"
    if candidate.exists():
        return candidate
    candidate2 = root_dir / "app" / "legal" / "provisions.yaml"
    if candidate2.exists():
        return candidate2
    return yaml_path

def load_provisions_config(yaml_path: Optional[Path] = None) -> LegalProvisionsConfig:
    global _REGISTRY
    if yaml_path is None:
        yaml_path = get_provisions_yaml_path()
    
    if not yaml_path.exists():
        raise FileNotFoundError(f"Legal provisions configuration file not found at: {yaml_path}")

    with open(yaml_path, "r", encoding="utf-8") as f:
        raw_data = yaml.safe_load(f)

    try:
        config = LegalProvisionsConfig(**raw_data)
        _REGISTRY = config
        return config
    except Exception as e:
        # Check if live mode requires failing hard
        live_mode = os.getenv("CHAINNETRA_MODE", "").upper() == "LIVE"
        if live_mode:
            raise RuntimeError(f"FATAL: Invalid legal provisions configuration in LIVE mode: {e}") from e
        raise

def get_legal_provisions_registry() -> LegalProvisionsConfig:
    global _REGISTRY
    if _REGISTRY is None:
        _REGISTRY = load_provisions_config()
    return _REGISTRY

def parse_date(d: Any) -> Optional[date]:
    if d is None:
        return None
    if isinstance(d, date):
        return d
    if isinstance(d, datetime):
        return d.date()
    if isinstance(d, str):
        try:
            return datetime.fromisoformat(d.replace("Z", "+00:00")).date()
        except ValueError:
            return datetime.strptime(d[:10], "%Y-%m-%d").date()
    return None

def get_citation(key: str, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Returns legal citation and applicability details based on context.
    Context keys:
      - offence_date: date | str | None
      - proceeding_pending_date: date | str | None
      - proceeding_pending_at_commencement: bool | None
      - as_of: date | str | None
    """
    registry = get_legal_provisions_registry()
    if key not in registry.provisions:
        raise KeyError(f"Legal provision key '{key}' not found in legal/provisions.yaml")

    provision = registry.provisions[key]
    commencement = registry.commencement.get("criminal_laws")
    commencement_date = commencement.date if commencement else date(2024, 7, 1)

    warnings: List[str] = []
    if commencement and commencement.verification != "primary":
        warnings.append("commencement date taken from secondary sources")

    if provision.verification == "unverified":
        warnings.append("citation unverified")

    current_citation = f"{provision.current_code} s.{provision.current_section}"
    legacy_citation = f"{provision.legacy_code} s.{provision.legacy_section}" if (provision.legacy_code and provision.legacy_section) else None

    context = context or {}
    offence_date = parse_date(context.get("offence_date"))
    pending_date = parse_date(context.get("proceeding_pending_date"))
    pending_flag = context.get("proceeding_pending_at_commencement")

    code_used: Literal["current", "legacy", "ambiguous"] = "current"
    citation: str = current_citation

    if provision.applicability_rule == "offence_date":
        if offence_date is None:
            code_used = "ambiguous"
            warnings.append("applicable code needs confirmation by the investigating officer")
            citation = f"{current_citation} (Current) / {legacy_citation or 'N/A'} (Legacy)"
        elif offence_date >= commencement_date:
            code_used = "current"
            citation = current_citation
        else:
            code_used = "legacy"
            citation = legacy_citation if legacy_citation else current_citation

    elif provision.applicability_rule == "proceeding_pending_at_commencement":
        # Check explicit flag or date
        is_pending = None
        if pending_flag is not None:
            is_pending = bool(pending_flag)
        elif pending_date is not None:
            is_pending = pending_date < commencement_date

        if is_pending is True:
            code_used = "legacy"
            citation = legacy_citation if legacy_citation else current_citation
        elif is_pending is False:
            code_used = "current"
            citation = current_citation
        else:
            code_used = "ambiguous"
            warnings.append("applicable code needs confirmation by the investigating officer")
            citation = f"{current_citation} (Current) / {legacy_citation or 'N/A'} (Legacy)"

    else:
        # None rule
        code_used = "current"
        citation = current_citation

    return {
        "key": key,
        "label": provision.label,
        "citation": citation,
        "code_used": code_used,
        "current_citation": current_citation,
        "legacy_citation": legacy_citation,
        "applicability_rule": provision.applicability_rule,
        "verification": provision.verification,
        "needs_legal_review": provision.needs_legal_review,
        "warnings": warnings,
        "note": provision.note,
        "disclaimer": LEGAL_DISCLAIMER
    }

def format_citation_footer(citations: List[Dict[str, Any]]) -> str:
    """
    Every generated document ends with a footer listing each citation used with its verification level.
    Anything not 'primary' is marked '(review required)'.
    """
    lines = [
        "---",
        f"Legal Notice: {LEGAL_DISCLAIMER}",
        "Statutory Citations Used:"
    ]
    seen = set()
    for c in citations:
        key = c.get("key")
        if key in seen:
            continue
        seen.add(key)
        cit = c.get("citation", "")
        ver = c.get("verification", "unverified")
        review_tag = "" if ver == "primary" else " (review required)"
        warn_str = f" - Warnings: {', '.join(c.get('warnings', []))}" if c.get("warnings") else ""
        lines.append(f" - {cit} [Verification: {ver}{review_tag}]{warn_str}")
    return "\n".join(lines)

def export_legal_notes_markdown(output_path: Optional[Path] = None) -> str:
    registry = get_legal_provisions_registry()
    commencement = registry.commencement.get("criminal_laws")
    comm_date_str = str(commencement.date) if commencement else "2024-07-01"
    comm_ver = commencement.verification if commencement else "secondary"

    md = [
        "# Legal Notes & Statutory Provisions Registry",
        "",
        "> [!IMPORTANT]",
        f"> **Global Legal Rule**: {LEGAL_DISCLAIMER}",
        "",
        "## Commencement Information",
        f"- **New Criminal Laws Effective Date**: `{comm_date_str}` (Verification: `{comm_ver}`)",
        f"- **Note**: {commencement.note if commencement else 'N/A'}",
        f"- **TODO**: {commencement.todo if commencement else 'N/A'}",
        "",
        "## Statutory Provisions Inventory",
        "",
        "| Key | Label | Current Code & Section | Legacy Code & Section | Rule | Verification | Review Required | Source |",
        "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |"
    ]

    for key, p in registry.provisions.items():
        curr = f"{p.current_code} s.{p.current_section}"
        leg = f"{p.legacy_code} s.{p.legacy_section}" if p.legacy_code else "None"
        rev = "Yes" if p.needs_legal_review else "No"
        md.append(f"| `{p.key}` | {p.label} | {curr} | {leg} | `{p.applicability_rule}` | `{p.verification}` | {rev} | {p.verified_source} |")

    md.extend([
        "",
        "## Open Questions for Counsel",
        "1. **BSA Section 63 Schedule Signatories**:",
        "   - Who is \"the Party\" for Part A when the instance is operated by a police unit?",
        "   - Part A recites lawful control and owned/maintained/managed/operated by the signer. This fits ChainNetra's own output (server/cloud) but not third-party explorer/API data. Does counsel require provider-side certificates for external blockchain explorer outputs?",
        "   - Whether the Part B expert should be internal or external, and whether to route formally through an Examiner of Electronic Evidence under Section 79A of the IT Act (per BSA s.39(2))?",
        "   - Where the system is hosted and who is formally designated as \"in charge\"?",
        "2. **Commencement Official Notification**:",
        "   - Official gazette commencement notification for Bharatiya Sakshya Adhiniyam, 2023 must be formally archived.",
        "3. **BNSS Section 106 vs Section 107 Seizure & Freezing**:",
        "   - High Courts have taken divergent views on whether police officers can debit-freeze bank/VASP accounts under BNSS Section 106 without a Magistrate's order. What jurisdictional requirements apply?",
        "4. **DPDP Act 2023 Commencement & Exemptions**:",
        "   - Core data fiduciary obligations commence ~May 2027. Section 17 investigation exemptions for State instrumentalities require specific government notifications. Compliance is not asserted until formally notified.",
        ""
    ])

    content = "\n".join(md)
    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
    return content

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Legal provisions CLI helper")
    parser.add_argument("--export-md", action="store_true", help="Export provisions to docs/LEGAL_NOTES.md")
    args = parser.parse_args()

    if args.export_md:
        out = Path("docs") / "LEGAL_NOTES.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        export_legal_notes_markdown(out)
        print(f"Exported legal notes to {out}")
    else:
        reg = get_legal_provisions_registry()
        print(f"Loaded {len(reg.provisions)} provisions successfully.")
